// Do not edit this file! It was automatically generated.

#ifndef GEN_TYPES_LD_H
#define GEN_TYPES_LD_H

#include "buildin:bindless.h"

// Postprocessing_UBO
RegisterUniform(PostprocessingUBO, {
	uint texture;
	float exposure;
	uint brightness_texture;
});

#define getPostprocessingUBO(handle) GetResource(PostprocessingUBO, handle)


// Camera_UBO
RegisterUniform(CameraUBO, {
	mat4 view;
	mat4 projection;
	vec3 position;
});

#define getCameraUBO(handle) GetResource(CameraUBO, handle)


// Text_UBO
RegisterUniform(TextUBO, {
	uint glyph;
	vec3 color;
});

#define getTextUBO(handle) GetResource(TextUBO, handle)


// Spot_Light
struct SpotLight {
	vec3 color;
	vec3 position;
};

// Directional_Light
struct DirectionalLight {
	uint camera;
	vec3 color;
	uint shadow;
};

// Light_Info_UBO
RegisterUniform(LightInfoUBO, {
	DirectionalLight dir_light;
	SpotLight[16] spot_lights;
});

#define getLightInfoUBO(handle) GetResource(LightInfoUBO, handle)


// Light_UBO
RegisterUniform(LightUBO, {
	vec3 diffuse_color;
	uint diffuse_texture;
	vec3 ambient;
	vec3 specular;
});

#define getLightUBO(handle) GetResource(LightUBO, handle)


// Base_Ubo
RegisterUniform(BaseUbo, {
	vec3 color;
	uint texture;
});

#define getBaseUBO(handle) GetResource(BaseUbo, handle)


// Primitive_UBO
RegisterUniform(PrimitiveUBO, {
	vec3 color;
});

#define getPrimitiveUBO(handle) GetResource(PrimitiveUBO, handle)


#endif